# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Cam130IuYx3LF3_6gDYLl8iVJ6ZHxAZX
"""

# #______ EMAIL VERIFICATION IN PYTHON _______



k,j,l =0,0,0

email = input("Enter your email: ") #s@g.in, sameer@gmail.com
if len(email)>=6:
    if email[0].isalpha():
        if("@" in email) and (email.count("@") == 1):
            if(email[-4]==".") ^ (email[-3]=="."):
                for i in email:
                    if i == i.isspace():
                        k=1
                    elif i.isalpha():
                        if i == i.upper():
                            j=1
                    elif i.isdigit():
                        continue
                    elif i == "_" or i == "." or i == "@":
                        continue
                    else:
                        l=1
                if k == 1 or j ==1 or l ==1 :
                    print("Wrong email!(5)")
            else:
                print("Wrong email!(4)")
        else:
            print("Wrong email!(3)")
    else:
        print("Wrong email!(2)")
else:
    print("Wrong email!(1)")